### ISSUE TITLE
Using casbin in SQL-Query

### ISSUE THREAD

**Issue by sundagy** [casbin/gorm-adapter#12]
Is there a way to use casbin policy checking in a WHERE part of SQL-query? For example, when selecting a list of entries.

**Comment by hsluoyz** [comment]
Hi @sundagy , Casbin can retrieve policy rules with a filter via the [GetFilteredNamedPolicy()] (https://casbin.org/docs/en/management-api#getfilterednamedpolicy) API, is this what you want? If not, can you provide a concrete example for your SQL's WHERE clause?

**Comment by sundagy** [comment]
select * from docs where user_id = ? and casbin_enforce(user_id, id, "read")

**Comment by hsluoyz** [comment]
Since Casbin is a part of SQL, I'm afraid that you can't use Casbin directly in SQL's WHERE. But you can first get all items from ``select * from docs where user_id = ?``, then get all permissions (ids that can be accessed by the user) via ``GetImplicitPermissionsForUser()`` API. Then take the intersection between these two sets. It will be the same result as your proposal.

**Comment by hsluoyz** [comment]
You can call: [GetImplicitPermissionsForUser()](https://casbin.org/docs/en/rbac#how-to-query-implicit-roles-or-permissions)
