### ISSUE TITLE
support customize table name

### ISSUE THREAD

**Issue by grunmin** [casbin/gorm-adapter#21]
Our app use multi permission models. I'll init multi Enforce instance while app startup, each Enforce load different model.
I use mysql to persist policy through gorm-adapter. I wanna to save policy to different table so each Enforce can load policy precisely.
How can I do that? Thanks

**Comment by hsluoyz** [comment]
Use Casbin-Server: https://github.com/casbin/casbin-server

**Comment by hsluoyz** [comment]
@grunmin I found that you only want to customize the table name. So can you send a PR about it? Also please keep the original usage way (via a default table name).

**Comment by hsluoyz** [comment]
Resolved in v2.0.1: https://github.com/casbin/gorm-adapter/releases/tag/v2.0.1

**Comment by berk-can** [comment]
Can you please let us edit table name as we want, not only adding a prefix

**Comment by hsluoyz** [comment]
@berk-can please send a PR

**Comment by berk-can** [comment]
I actually downloaded project and edited function myself
```
func (c *CasbinRule) TableName() string {
	return c.TablePrefix
}
```
as above, but this prevents adding prefix to table name as it uses TablePrefix as actual name of table, and it fails if not provided, so I dont know how to make an edit to both preserve prefix and add functionality to change table name altogether.

But if you want I can change TablePrefix to TableName which I think would be more usable because if someone only wants to add prefix zhe can easily use "desired_prefix_casbin_rule" as tableName, also I can make it optional field (,tableName ...string) so that if not defined table name will be "casbin_rule" and there will be no separate functions
