### ISSUE TITLE
Why doesn't casbin_rule add an auto increment primary key?

### ISSUE THREAD

**Issue by aofengli** [casbin/gorm-adapter#35]
One should be added from a performance perspective

**Comment by aofengli** [comment]
I don’t quite understand why you don’t increase the primary key field. According to the mysql innodb index design, it is recommended to provide an ID primary key

**Comment by nodece** [comment]
I guess the Casbin don't need the ID primary key.

**Comment by hsluoyz** [comment]
@aofengli can you make a PR to add an increment primary key?

**Comment by hsluoyz** [comment]
@00LT00 can you take this issue?

**Comment by 00LT00** [comment]
I'm learning about it and solving it as soon as possible

**Comment by 00LT00** [comment]
1. When casbin is loaded, it has already loaded from database to memory. So the database is not selected during runtime. The primary key has no effect on select operations. 
2. Because the gorm-adapter just is a tool to get policy. The struct in memory must be the same as "policy.csv". In fact, the primary key cannot be used at all when deleting.

In summary, I think we shouldn't add ID primary key for casbin.
What do you think? @aofengli @hsluoyz

**Comment by hsluoyz** [comment]
> I don’t quite understand why you don’t increase the primary key field. According to the mysql innodb index design, it is recommended to provide an ID primary key

@aofengli can you make a PR to fix it?

**Comment by nodece** [comment]
@hsluoyz We should add unique index.

**Comment by hsluoyz** [comment]
Can anyone work on a PR?

**Comment by 00LT00** [comment]
@hsluoyz @nodece add unique index

**Comment by hsluoyz** [comment]
PR made: https://github.com/casbin/gorm-adapter/pull/54
