### ISSUE TITLE
Panic when trying to connect

### ISSUE THREAD

**Issue by therecluse26** [casbin/gorm-adapter#6]
Hi, I'm receiving this error when I try to call NewAdapter using correct (url encoded) credentials.

`panic: mssql: Incorrect syntax near 'casbin'.`

I don't think this is an issue with my connection string, but what do you think? This is how I'm calling it.

```go
a := gormadapter.NewAdapter("mssql", "sqlserver://"+username+":"+pass+"@remote_url:1433?database=dbname")
```

**Comment by hsluoyz** [comment]
We didn't test against SQL server in the development. So the connect string parsing is probably buggy for SQL server. What SQL server version are you using? Because I need to install one and see why it doesn't work.

You can wait for me to debug this. Maybe it will take 1-2 days. You can also help debug it by yourself if you want. Debug into this adapter, see how the connect string doesn't work for SQL server.
