### ISSUE TITLE
*gormadapter.Adapter is not persist.UpdatableAdapter: missing method UpdatePolicies

### ISSUE THREAD

**Issue by saeedgeek** [casbin/gorm-adapter#81]
panic: interface conversion: *gormadapter.Adapter is not persist.UpdatableAdapter: missing method UpdatePolicies
in version v2.25.2
its work for me in v2.21.0
thanks

**Comment by aryan828** [comment]
@saeedgeek Can you both the working and non-working versions of your code so that I can track the error. 
Also @hsluoyz , have you implemented the UpdatePolicy() and UpdatePolicies() API, because it is mentioned in [docs](https://casbin.org/docs/en/management-api#updatepolicy) but what I found was 
`func (a *Adapter) UpdatePolicy(sec string, ptype string, oldRule, newPolicy []string) error {
	return errors.New("not implemented")
}` 
for [UpdatePolicy](https://github.com/casbin/casbin/blob/86d48b589606a67f8dc3c51486e8daa1b743f579/persist/file-adapter/adapter.go#L35) and 
`func (a *Adapter) UpdatePolicies(sec string, ptype string, oldRules, newRules [][]string) error {
	return errors.New("not implemented")
}`
for [UpdatePolicies](https://github.com/casbin/casbin/blob/86d48b589606a67f8dc3c51486e8daa1b743f579/persist/file-adapter/adapter.go#L39) in latest version. And UpdatePolicies was missing in v2.21.0

**Comment by hsluoyz** [comment]
@aryan828 yeah, so we need to implement `UpdatePolicies()`.
